name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku deploy
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "branch-dictator"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          buildpack: "heroku/nodejs"
